/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as R404RouteImport } from './routes/404'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as ManualIndexRouteImport } from './routes/manual.index'
import { Route as ManualSlugRouteImport } from './routes/manual.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsYearMonthSlugRouteImport } from './routes/news.$year.$month.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualIndexRoute = ManualIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManualRoute,
} as any)
const ManualSlugRoute = ManualSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ManualRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsYearMonthSlugRoute = NewsYearMonthSlugRouteImport.update({
  id: '/news/$year/$month/$slug',
  path: '/news/$year/$month/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/manual': typeof ManualRouteWithChildren
  '/teams': typeof TeamsRoute
  '/themes': typeof ThemesRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/': typeof ManualIndexRoute
  '/news/': typeof NewsIndexRoute
  '/news/$year/$month/$slug': typeof NewsYearMonthSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/teams': typeof TeamsRoute
  '/themes': typeof ThemesRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual': typeof ManualIndexRoute
  '/news': typeof NewsIndexRoute
  '/news/$year/$month/$slug': typeof NewsYearMonthSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/manual': typeof ManualRouteWithChildren
  '/teams': typeof TeamsRoute
  '/themes': typeof ThemesRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/': typeof ManualIndexRoute
  '/news/': typeof NewsIndexRoute
  '/news/$year/$month/$slug': typeof NewsYearMonthSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/manual'
    | '/teams'
    | '/themes'
    | '/manual/$slug'
    | '/manual/'
    | '/news/'
    | '/news/$year/$month/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/teams'
    | '/themes'
    | '/manual/$slug'
    | '/manual'
    | '/news'
    | '/news/$year/$month/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/manual'
    | '/teams'
    | '/themes'
    | '/manual/$slug'
    | '/manual/'
    | '/news/'
    | '/news/$year/$month/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  ManualRoute: typeof ManualRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  ThemesRoute: typeof ThemesRoute
  NewsIndexRoute: typeof NewsIndexRoute
  NewsYearMonthSlugRoute: typeof NewsYearMonthSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/': {
      id: '/manual/'
      path: '/'
      fullPath: '/manual/'
      preLoaderRoute: typeof ManualIndexRouteImport
      parentRoute: typeof ManualRoute
    }
    '/manual/$slug': {
      id: '/manual/$slug'
      path: '/$slug'
      fullPath: '/manual/$slug'
      preLoaderRoute: typeof ManualSlugRouteImport
      parentRoute: typeof ManualRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$year/$month/$slug': {
      id: '/news/$year/$month/$slug'
      path: '/news/$year/$month/$slug'
      fullPath: '/news/$year/$month/$slug'
      preLoaderRoute: typeof NewsYearMonthSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManualRouteChildren {
  ManualSlugRoute: typeof ManualSlugRoute
  ManualIndexRoute: typeof ManualIndexRoute
}

const ManualRouteChildren: ManualRouteChildren = {
  ManualSlugRoute: ManualSlugRoute,
  ManualIndexRoute: ManualIndexRoute,
}

const ManualRouteWithChildren =
  ManualRoute._addFileChildren(ManualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  ManualRoute: ManualRouteWithChildren,
  TeamsRoute: TeamsRoute,
  ThemesRoute: ThemesRoute,
  NewsIndexRoute: NewsIndexRoute,
  NewsYearMonthSlugRoute: NewsYearMonthSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
